version: "2"

# https://hub.docker.com/r/centos/systemd/
# https://hub.docker.com/r/jrei/systemd-ubuntu

services:
  # web:
  #  image: nginx
  #  volumes:
  #    - ./html:/usr/share/nginx/html
  #  ports:
  #    - "80:80"
  #  environment:
  #    - NGINX_PORT=80
  sm:
    container_name: saltmaster
    image: kajigga/sm-cn-7:0.1
    build: 
      context: ./sm-cn-7
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "4505"
      - "4506"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "../master.d:/etc/salt/master.d/:z"
      - "../minion.d:/etc/salt/minion.d:z"
  centos:
    container_name: centos
    image: kajigga/smin-cn-7:0.1
    build:
      context: ./smin-cn-7
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "../minion.d:/etc/salt/minion.d/:z"
  ubuntu:
    container_name: ubuntu
    image: kajgiga/smin-ub-18:0.1
    build:
      context: ./smin-ub-18
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "../minion.d:/etc/salt/minion.d/:z"
