version: "3"


services:
  sm:
    container_name: saltmaster
    image: kajigga/sm-cn-7:0.3
    build: 
      context: ./sm-cn-7
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "4505"
      - "4506"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "../master.d:/etc/salt/master.d/:z"
      - "../minion.d:/etc/salt/minion.d:z"
  centos:
    container_name: centos
    image: kajigga/smin-cn-7:0.3
    build:
      context: ./smin-cn-7
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "../minion.d:/etc/salt/minion.d/:z"
  ubuntu:
    container_name: ubuntu
    image: kajigga/smin-ub-18:0.3
    build:
      context: ./smin-ub-18
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - sm
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "../minion.d:/etc/salt/minion.d/:z"
